### ISSUE TITLE
It is not Working

### ISSUE THREAD

**Issue by anandraj8756** [Aqsa-K/Car-Number-Plate-Detection-OpenCV-Python#1]
new, cnts, _) = cv2.findContours(edged.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by Asmeble** [comment]
maybe replace "_)" with "_"?

**Comment by amaadmirza** [comment]
change this line like 

cnts, new = cv2.findContours(edged.copy(), cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
